---
title: "What are the top 10 nationalities with the highest number of goals scored by their top 5 scorers?"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
library(janitor)
library(forcats)
library(purrr)
library(webshot)
library(graphics)
library(RColorBrewer)
library(DataExplorer)
library(magrittr)
library(sf)
library(leaflet)
library(ggridges)
library(tigris)
library(ggthemes)
library(htmltools)
library(htmlwidgets)
library(readr)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
  fig.height = 14, 
  fig.width = 10,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = TRUE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5,face = "bold"), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


```{r data_read, include = FALSE, echo = FALSE}
# Load data

# Load soccer stats data
soccer.df <- read_csv(file = './data/soccer.csv') %>%
  filter(!is.na(player))

# Load country names data set (with abbreviations)
ioc_country.df <- read_csv(url("https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv")) %>%
  select(FIFA,official_name_en) %>%
  rename(Country=official_name_en,NOC=FIFA)

# Load country coordinates (geometry) data set
world_boundaries3.df <- read_csv("./data/world-coordinates-data.csv") %>%
janitor::clean_names() 

```

```{r, echo = FALSE, include = FALSE}
# Do data wrangling and create needed variables
soccer.df <- soccer.df %>%
  mutate(value_millions = (value/1000000)) %>%
  separate(nationality, into = c("nationality", "country_origin"), sep = " ")

# Create variable ranking of players by value and goals
soccer.df <- soccer.df %>%
  arrange(desc(value)) %>%
  mutate(ranking_player_value = 1:length(player)) %>%
  arrange(desc(goals)) %>%
  mutate(ranking_player_goals = 1:length(player))

# Separating geometry into latitude and longitude

world_boundaries3.df <- world_boundaries3.df %>%
  separate(geo_point_coord, into = c("lat", "long"), sep = ",") %>%
  mutate(lat = as.numeric(lat),long = as.numeric(long))


# Join country's names

soccer_world.df <- left_join(
  soccer.df,
  ioc_country.df,
  by = c("country_origin" = "NOC") #zipcode in first, zip_code second
)


# Edit names for countries from United Kingdom, and other countries with special characters

soccer_world.df <- soccer_world.df %>%
  mutate(Country = ifelse(country_origin %in% "ENG"|country_origin %in% "WAL"|country_origin %in% "SCO"|country_origin %in% "NIR","United Kingdom",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "CUW","Curaçao",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "KVX","Kosovo",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "CIV","Ivory Coast",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "CUW","Curacao",Country)) %>%
  mutate(Country = ifelse(nationality %in% "GPE","Curacao",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "REU","Reunion",Country))


# Joining soccer_world.df with world boundaries data

soccer_world3.df <- inner_join(
  soccer_world.df, 
  world_boundaries3.df, 
  by = c("Country" = "english_name") 
)
```

**Figure 3** and **Table 3** show the Top 10 Countries by the number of Goals from their Top 5 Scorers in 2018/2019 season.


```{r, echo = FALSE, include = TRUE, message = FALSE, warning = FALSE}
## Q3 - 

# Top 5 scorers by country
top5_players <- soccer_world.df %>%
  group_by(country_origin, player) %>%
  summarise(total_goals = sum(goals)) %>%
  arrange(country_origin, desc(total_goals)) %>%
  slice(1:5) %>%
  ungroup()

# Top 10 coountries by number of goals scored by top 5 scorers
top10_countries <- soccer_world.df %>%
  filter(player %in% top5_players$player) %>%
  group_by(country_origin) %>%
  summarise(total_goals_country = sum(goals)) %>%
  arrange(desc(total_goals_country)) %>%
  slice(1:10)

# GT table
goals_10countries <- soccer_world.df %>%
  filter(country_origin %in% top10_countries$country_origin,
         player %in% top5_players$player) %>%
  group_by(Country) %>%
  mutate(total_goals_country = sum(goals)) %>%
  select(player, Country, squad, league, goals, total_goals_country) %>%
  arrange(desc(total_goals_country)) %>%
  select(player, Country, squad, league, goals) %>%
  rename("Player" = player, "Team" = squad, "League" = league, "Goals" = goals) %>%
  gt() %>%
  summary_rows(
    groups  = TRUE,
    columns = contains(c("Goals")),
    fns = list("# Goals per Country" = ~sum(., na.rm = TRUE)),
    formatter = fmt_number,
    decimals  = 0,
    suffixing = TRUE
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_column_labels(everything())
  ) %>% 
  cols_align(align = c("center"), columns = everything()) %>%
  opt_table_lines(extent = "default") %>%
  tab_source_note("*Data merged from transfermarkt.de and fbref.com for 2018/19 season by Rafael Stepien and available on Kaggle*") %>%
  data_color(
    columns = "Goals",
    colors = scales::col_numeric(
      palette = c("PuBu"),
      domain  = c(0, 40))) %>%
  tab_header(title = md("**Table 3. Top 5 Scorers in top 10 countries in 2018/2019 season**"))

goals_10countries
```

***

```{r, echo = FALSE, include = TRUE, message = FALSE, warning = FALSE}

# Q3
# Plot using ggplot and ggplotly
goals_10countries_ggplot <- soccer_world.df %>%
  filter(country_origin %in% top10_countries$country_origin,
         player %in% top5_players$player) %>%
  group_by(Country) %>%
  mutate(total_goals_country = sum(goals)) %>%
  ungroup() %>%
  rename("Goals" = goals) %>%
  mutate(player = fct_reorder(player, Goals)) %>%
  mutate(
    text_label = str_c("\nTeam: ", squad,
                       "\nValue (M): ", scales::dollar(value_millions),
                       "\nAssists: ", assists,
                       "\nPosition: ", position2)) %>%
  ggplot() +
  geom_col(aes(x = player, y = Goals, fill = Goals, text = text_label)) +
  facet_wrap(~Country, scales = "free", ncol = 2) +
  scale_fill_viridis_c() +
  labs(title = "Figure 3. Top 5 Scorers in top 10 countries in 2018/2019 season",
       x = "Player",
       y = "Number of Goals") +
  theme(legend.position = "right") +
  coord_flip() + theme(panel.spacing = unit(7, "lines"))

ggplotly(goals_10countries_ggplot, tooltip = "text") %>% layout(width = 900,heights = 1000,margin = list(b = 90))
```