---
title: "The Best Performing Soccer Players in the Top 5 European Leagues"
author: "Felipe Pena and Maykon da Silva"
output: flexdashboard::flex_dashboard
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
library(janitor)
library(forcats)
library(purrr)
library(webshot)
library(graphics)
library(RColorBrewer)
library(DataExplorer)
library(magrittr)
library(sf)
library(leaflet)
library(ggridges)
library(tigris)
library(ggthemes)
library(htmltools)
library(htmlwidgets)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
  fig.height = 8, 
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = TRUE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


```{r data_read, include = FALSE, echo = FALSE}
# Load data

# Load soccer stats data
soccer.df <- read_csv(file = './data/soccer.csv') %>%
  filter(!is.na(player))

# Load country names data set (with abbreviations)
ioc_country.df <- read_csv(url("https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv")) %>%
  select(FIFA,official_name_en) %>%
  rename(Country=official_name_en,NOC=FIFA)

# Load country coordinates (geometry) data set
world_boundaries3.df <- read_csv("./data/world-coordinates-data.csv") %>%
janitor::clean_names() 


```

```{r, echo = FALSE, include = FALSE}
# Do data wrangling and create needed variables
soccer.df <- soccer.df %>%
  mutate(value_millions = (value/1000000)) %>%
  separate(nationality, into = c("nationality", "country_origin"), sep = " ")

# Create variable ranking of players by value and goals
soccer.df <- soccer.df %>%
  arrange(desc(value)) %>%
  mutate(ranking_player_value = 1:length(player)) %>%
  arrange(desc(goals)) %>%
  mutate(ranking_player_goals = 1:length(player))

# Separating geometry into latitude and longitude

world_boundaries3.df <- world_boundaries3.df %>%
  separate(geo_point_coord, into = c("lat", "long"), sep = ",") %>%
  mutate(lat = as.numeric(lat),long = as.numeric(long))


# Join country's names

soccer_world.df <- left_join(
  soccer.df,
  ioc_country.df,
  by = c("country_origin" = "NOC") #zipcode in first, zip_code second
)


# Edit names for countries from United Kingdom, and other countries with special characters

soccer_world.df <- soccer_world.df %>%
  mutate(Country = ifelse(country_origin %in% "ENG"|country_origin %in% "WAL"|country_origin %in% "SCO"|country_origin %in% "NIR","United Kingdom",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "CUW","Curaçao",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "KVX","Kosovo",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "CIV","Ivory Coast",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "CUW","Curacao",Country)) %>%
  mutate(Country = ifelse(nationality %in% "GPE","Curacao",Country)) %>%
  mutate(Country = ifelse(country_origin %in% "REU","Reunion",Country))


# Joining soccer_world.df with world boundaries data

soccer_world3.df <- inner_join(
  soccer_world.df, 
  world_boundaries3.df, 
  by = c("Country" = "english_name") 
)
```

Column {.tabset}
-----------------------------------------------------------------------

### Question 1 - GT Table

```{r, echo = FALSE}
## Q1:

# GT Table
soccer_world.df %>%
  mutate(Position = ifelse(grepl("Forward", position2),"Forward",position2)) %>%
  mutate(Position = ifelse(grepl("Midfielder", Position),"Midfielder",Position)) %>%
  mutate(Position = ifelse(grepl("Defender", Position),"Defender",Position)) %>%
  group_by(Position) %>%
  arrange(ranking_player_value) %>%
  slice(1:5) %>%
  mutate(average_value_top_5 = round((mean(value,na.rm = TRUE)),2)) %>%
  arrange(desc(average_value_top_5)) %>%
  select(c(player,squad,Country,Position,goals,assists,value)) %>%
  rename("Player" = player,"Team" = squad,"Goals" = goals,"Assists" = assists,"Value (USD)" = value) %>%
  gt() %>%
  fmt_number(
    columns = where(is.numeric),
    decimals = 0 ,
    suffixing = TRUE) %>%
  cols_align(
    align = "center",
    columns = everything()) %>%
  cols_align(
    align = "center",
    columns = everything()) %>%
  data_color(
    columns =Goals,
    colors = scales::col_numeric(
      palette = c("PuBu"),
      domain  = c(min(Goals), max(Goals)))) %>%
  data_color(
    columns =Assists,
    colors = scales::col_numeric(
      palette = c("PuBu"),
      domain  = c(min(Assists), max(Assists)))) %>%
  data_color(
    columns =`Value (USD)`,
    colors = scales::col_numeric(
      palette = c("Purples"),
      domain  = c(min(`Value (USD)`), max(`Value (USD)`)))) %>%
  summary_rows(
    groups  = TRUE,
    columns = where(is.numeric),
    fns = list("# Average top 5" = ~mean(., na.rm = TRUE)),
    formatter = fmt_number,
    decimals  = 0,
    suffixing = TRUE) %>%
  tab_header(title = md("**Top 5 most valuable players by position**")) %>%
  tab_source_note("*Data merged from transfermarkt.de and fbref.com by Rafael Stepien and available on Kaggle*")
```

### Question 1 - GGPLOT
```{r, echo = FALSE}

# Plot most valuable players by team
# Plot most valuable players by league

Plot_valuable_players <- soccer_world.df %>%
  group_by(league) %>%
  arrange(ranking_player_value) %>%
  slice(1:5) %>%
  mutate(average_value_top_5 = round((mean(value,na.rm = TRUE)),2)) %>%
  arrange(desc(average_value_top_5)) %>%
  mutate(
    text_label = str_c("Value, Nationality, and Squad and More",
                       "\nTeam: ", squad,
                       "\nValue: ", value_millions,
                       "\nGoals: ", goals,
                       "\nAssists: ", assists,
                       "\nPosition: ", position2)) %>%
  rename("Player" = player,"Team" = squad,"Value" = value_millions,"Goals"=goals) %>%
  ggplot() +
  geom_col(aes(x = Value, y = fct_reorder(Player,value), fill=Goals, text = text_label)) +
  labs(
    x     = "Value (millions USD)",
    y     = "Player",
    title = "Most valuable players in top 5 European Leagues" ) +
  scale_fill_viridis_c() +
  theme(axis.text.x = element_text(angle   = 90,
                                   vjust = 0.5,
                                   hjust = 1,
                                   size  = 10)) +
  facet_wrap( ~league , scales = "free",ncol=3) +
  theme(panel.spacing = unit(2, "lines"))

# Transform into a ggplotly object
ggplotly(Plot_valuable_players, tooltip = "text")
```

### Question 2 - GT Table

```{r, echo = FALSE}
## Q2 - What are the soccer teams (squad) and leagues for which the top scorers played?

# GT Table
soccer.df %>%
  select(player, squad, league, goals) %>%
  arrange(desc(goals)) %>%
  slice(1:20) %>%
  rename(
    "Player" = player, 
    "Team"   = squad, 
    "League" = league, 
    "Goals"  = goals) %>%
  gt() %>%
  tab_header(title = md("**Top 20 Scorers - Teams and Leagues**")) %>%
  data_color(columns = "Goals",
             colors = scales::col_numeric(
               palette = c("Greys"),
               domain  = c(10, 40))) %>%
  data_color(columns = "League",
             colors = scales::col_factor(
               palette = c("viridis"),
               domain  = c("La Liga", "Ligue 1", "Serie A", "Bundesliga", "Premier League"))) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_column_labels(everything())
  ) %>% 
  cols_align(align = c("center"), columns = everything()) %>%
  opt_table_lines(extent = "default") %>%
  tab_options(
    column_labels.border.top.color = "black",
    column_labels.border.top.width = px(2),
    column_labels.border.bottom.color = "black",
    table_body.hlines.color   = "white",
    column_labels.border.bottom.style = "black"
  ) %>%
  tab_source_note("*Data merged from transfermarkt.de and fbref.com for 2018/19 season by Rafael Stepien and available on Kaggle*")
```

### Question 2 - GGPLOTLY

```{r, echo = FALSE}
## Q2
# GGPlot with GGPlotly
q2_ggplot <- soccer.df %>%
  select(player, squad, league, country_origin, goals, assists, value_millions, position2) %>%
  arrange(desc(goals)) %>%
  slice(1:20) %>%
  mutate(player = fct_reorder(player, desc(goals))) %>%
  mutate(
    text_label = str_c("\nTeam: ", squad)) %>%
  rename("League" = league) %>%
  ggplot() +
    geom_col(aes(x = player, y = goals, fill = League, text = text_label)) +
  labs(
    x     = "Player",
    y     = "Goals",
    title = "Number of Goals by Player"
  ) +
  scale_fill_viridis_d("League") +
  theme(axis.text.x = element_text(angle   = 0,
                                   vjust = 0.5,
                                   hjust = 1,
                                   size  = 10)) +
  coord_flip()

ggplotly(q2_ggplot, tooltip = "text")
```

### Question 3 - GT Table

```{r, echo = FALSE, include = TRUE, message = FALSE, warning = FALSE}
## Q3 - 

# Top 5 scorers by country
top5_players <- soccer_world.df %>%
  group_by(country_origin, player) %>%
  summarise(total_goals = sum(goals)) %>%
  arrange(country_origin, desc(total_goals)) %>%
  slice(1:5) %>%
  ungroup()

# Top 10 coountries by number of goals scored by top 5 scorers
top10_countries <- soccer_world.df %>%
  filter(player %in% top5_players$player) %>%
  group_by(country_origin) %>%
  summarise(total_goals_country = sum(goals)) %>%
  arrange(desc(total_goals_country)) %>%
  slice(1:10)

# GT table
goals_10countries <- soccer_world.df %>%
  filter(country_origin %in% top10_countries$country_origin,
         player %in% top5_players$player) %>%
  group_by(Country) %>%
  mutate(total_goals_country = sum(goals)) %>%
  select(player, Country, squad, league, goals, total_goals_country) %>%
  arrange(desc(total_goals_country)) %>%
  select(player, Country, squad, league, goals) %>%
  rename("Player" = player, "Team" = squad, "League" = league, "Goals" = goals) %>%
  gt() %>%
  summary_rows(
    groups  = TRUE,
    columns = contains(c("Goals")),
    fns = list("# Goals per Country" = ~sum(., na.rm = TRUE)),
    formatter = fmt_number,
    decimals  = 0,
    suffixing = TRUE
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_column_labels(everything())
  ) %>% 
  cols_align(align = c("center"), columns = everything()) %>%
  opt_table_lines(extent = "default") %>%
  tab_source_note("*Data merged from transfermarkt.de and fbref.com for 2018/19 season by Rafael Stepien and available on Kaggle*") %>%
  data_color(
    columns = "Goals",
    colors = scales::col_numeric(
      palette = c("PuBu"),
      domain  = c(0, 40))) %>%
  tab_header(title = md("**Top 10 Countries by their 5 Top Scorers**"))

goals_10countries
```

### Question 3 - GGPLOTLY

```{r, echo = FALSE, include = TRUE, message = FALSE, warning = FALSE}

# Q3
# Plot using ggplot and ggplotly
goals_10countries_ggplot <- soccer_world.df %>%
  filter(country_origin %in% top10_countries$country_origin,
         player %in% top5_players$player) %>%
  group_by(Country) %>%
  mutate(total_goals_country = sum(goals)) %>%
  ungroup() %>%
  rename("Goals" = goals) %>%
  mutate(player = fct_reorder(player, Goals, .desc = TRUE)) %>%
  mutate(
    text_label = str_c("\nTeam: ", squad,
                       "\nValue (M): ", scales::dollar(value_millions),
                       "\nAssists: ", assists,
                       "\nPosition: ", position2)) %>%
  ggplot() +
  geom_col(aes(x = player, y = Goals, fill = Goals, text = text_label)) +
  facet_wrap(~Country, scales = "free", ncol = 2) +
  scale_fill_viridis_c() +
  labs(title = "Top 10 Countries by No. of Goals from their Top 5 Scorers",
       x = "Player",
       y = "Number of Goals") +
  theme(legend.position = "right") +
  coord_flip()

ggplotly(goals_10countries_ggplot, tooltip = "text")
```